import { Student, StaffMember, AccessRecord, DirectNotice, Announcement, SchoolEvent } from './types';

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'alu-001',
    enrollmentId: 'ALU-2026-001',
    fullName: 'Sofía Mendoza Sanabria',
    grade: '3°',
    group: 'A',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Vita Aurora Sanabria Lara',
    tutorPhone: '+52 55 4920 1834',
    tutorEmail: 'vita.sanabria@email.com',
    status: 'Activo',
    bloodType: 'O+',
    emergencyContact: 'Carlos Mendoza (Padre) - +52 55 1234 5678',
    medicalNotes: 'Alergia leve a la penicilina.',
    qrCodeValue: 'ESC-ALU-2026-001-SOFIA-MENDOZA',
  },
  {
    id: 'alu-002',
    enrollmentId: 'ALU-2026-002',
    fullName: 'Mateo Alejandro Gómez Ruiz',
    grade: '3°',
    group: 'A',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Laura Ruiz Castro',
    tutorPhone: '+52 55 7712 9043',
    tutorEmail: 'laura.ruiz@email.com',
    status: 'Activo',
    bloodType: 'A+',
    emergencyContact: 'Alberto Gómez - +52 55 9988 7766',
    medicalNotes: 'Usa lentes para lectura.',
    qrCodeValue: 'ESC-ALU-2026-002-MATEO-GOMEZ',
  },
  {
    id: 'alu-003',
    enrollmentId: 'ALU-2026-003',
    fullName: 'Valentina Morales Herrera',
    grade: '1°',
    group: 'B',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Ernesto Morales Vega',
    tutorPhone: '+52 55 6321 8890',
    tutorEmail: 'ernesto.m@email.com',
    status: 'Activo',
    bloodType: 'B+',
    emergencyContact: 'Rosa Herrera - +52 55 4433 2211',
    qrCodeValue: 'ESC-ALU-2026-003-VALENTINA-MORALES',
  },
  {
    id: 'alu-004',
    enrollmentId: 'ALU-2026-004',
    fullName: 'Santiago David López Navarro',
    grade: '4°',
    group: 'A',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Mariana Navarro Silva',
    tutorPhone: '+52 55 8899 4411',
    tutorEmail: 'mariana.navarro@email.com',
    status: 'Activo',
    bloodType: 'O-',
    emergencyContact: 'David López - +52 55 3322 1100',
    medicalNotes: 'Asma leve, lleva inhalador en mochila.',
    qrCodeValue: 'ESC-ALU-2026-004-SANTIAGO-LOPEZ',
  },
  {
    id: 'alu-005',
    enrollmentId: 'ALU-2026-005',
    fullName: 'Camila Elizabeth Torres Ortiz',
    grade: '2°',
    group: 'C',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Patricia Ortiz Valdés',
    tutorPhone: '+52 55 3344 7788',
    tutorEmail: 'patricia.ortiz@email.com',
    status: 'Activo',
    bloodType: 'AB+',
    emergencyContact: 'Ricardo Torres - +52 55 6677 8899',
    qrCodeValue: 'ESC-ALU-2026-005-CAMILA-TORRES',
  },
  {
    id: 'alu-006',
    enrollmentId: 'ALU-2026-006',
    fullName: 'Leonardo Daniel Cruz Méndez',
    grade: '5°',
    group: 'B',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Gonzalo Cruz Fuentes',
    tutorPhone: '+52 55 2211 4455',
    tutorEmail: 'gonzalo.cruz@email.com',
    status: 'Activo',
    bloodType: 'O+',
    emergencyContact: 'Teresa Méndez - +52 55 5544 3322',
    qrCodeValue: 'ESC-ALU-2026-006-LEONARDO-CRUZ',
  },
  {
    id: 'alu-007',
    enrollmentId: 'ALU-2026-007',
    fullName: 'Regina Isabela Flores Pacheco',
    grade: '6°',
    group: 'A',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Irma Pacheco Solís',
    tutorPhone: '+52 55 9900 1122',
    tutorEmail: 'irma.pacheco@email.com',
    status: 'Activo',
    bloodType: 'A-',
    emergencyContact: 'Eduardo Flores - +52 55 8877 6655',
    qrCodeValue: 'ESC-ALU-2026-007-REGINA-FLORES',
  },
  {
    id: 'alu-008',
    enrollmentId: 'ALU-2026-008',
    fullName: 'Emiliano José Castillo Lara',
    grade: '6°',
    group: 'B',
    shift: 'Matutino',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=250',
    tutorName: 'Javier Castillo Morales',
    tutorPhone: '+52 55 7766 5544',
    tutorEmail: 'javier.castillo@email.com',
    status: 'Activo',
    bloodType: 'O+',
    emergencyContact: 'Adriana Lara - +52 55 1122 3344',
    qrCodeValue: 'ESC-ALU-2026-008-EMILIANO-CASTILLO',
  }
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'stf-001',
    fullName: 'Prof. Roberto Alarcón Díaz',
    roleTitle: 'Responsable de Puerta Principal',
    subjectOrArea: 'Control de Acceso & Turno Matutino',
    assignedGate: 'Portón Principal (Entrada General)',
    phone: '+52 55 1199 2288',
    email: 'roberto.alarcon@escuela.edu.mx',
    shift: 'Matutino',
    status: 'En Turno',
    photoUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'stf-002',
    fullName: 'Mtra. Elena Bustamante Ramos',
    roleTitle: 'Docente Titular 3° A',
    subjectOrArea: 'Educación Primaria / Matemáticas',
    assignedGate: 'Portón 2 (Primaria / Vehicular)',
    phone: '+52 55 3388 4477',
    email: 'elena.bustamante@escuela.edu.mx',
    shift: 'Matutino',
    status: 'En Turno',
    photoUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'stf-003',
    fullName: 'Lic. Fernando Quiroz Vega',
    roleTitle: 'Prefecto y Supervisor de Accesos',
    subjectOrArea: 'Seguridad Escolar & Salidas',
    assignedGate: 'Portón 3 (Peatonal / Secundaria)',
    phone: '+52 55 5566 7788',
    email: 'fernando.quiroz@escuela.edu.mx',
    shift: 'Completo',
    status: 'En Turno',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=250',
  },
  {
    id: 'stf-004',
    fullName: 'Dra. Carmen Estrada Montes',
    roleTitle: 'Dirección Académica',
    subjectOrArea: 'Control Escolar y Gestión',
    assignedGate: 'Portón Principal (Entrada General)',
    phone: '+52 55 8899 0011',
    email: 'carmen.estrada@escuela.edu.mx',
    shift: 'Completo',
    status: 'En Turno',
    photoUrl: 'https://images.unsplash.com/photo-1580894732444-8ecded7900cd?auto=format&fit=crop&q=80&w=250',
  },
];

export const INITIAL_ACCESS_RECORDS: AccessRecord[] = [
  {
    id: 'acc-001',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    enrollmentId: 'ALU-2026-001',
    grade: '3°',
    group: 'A',
    type: 'Entrada',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    formattedTime: '07:42 AM',
    date: new Date().toISOString().split('T')[0],
    status: 'on_time',
    gate: 'Portón Principal (Entrada General)',
    registeredBy: 'Prof. Roberto Alarcón Díaz',
    notes: 'Ingreso puntual con uniforme completo.',
  },
  {
    id: 'acc-002',
    studentId: 'alu-002',
    studentName: 'Mateo Alejandro Gómez Ruiz',
    enrollmentId: 'ALU-2026-002',
    grade: '3°',
    group: 'A',
    type: 'Entrada',
    timestamp: new Date(Date.now() - 3600000 * 1.8).toISOString(),
    formattedTime: '07:49 AM',
    date: new Date().toISOString().split('T')[0],
    status: 'on_time',
    gate: 'Portón Principal (Entrada General)',
    registeredBy: 'Prof. Roberto Alarcón Díaz',
  },
  {
    id: 'acc-003',
    studentId: 'alu-003',
    studentName: 'Valentina Morales Herrera',
    enrollmentId: 'ALU-2026-003',
    grade: '1°',
    group: 'B',
    type: 'Entrada',
    timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    formattedTime: '08:05 AM',
    date: new Date().toISOString().split('T')[0],
    status: 'late',
    gate: 'Portón 2 (Primaria / Vehicular)',
    registeredBy: 'Mtra. Elena Bustamante Ramos',
    notes: 'Retardo de 5 minutos por tráfico.',
  },
  {
    id: 'acc-004',
    studentId: 'alu-004',
    studentName: 'Santiago David López Navarro',
    enrollmentId: 'ALU-2026-004',
    grade: '4°',
    group: 'A',
    type: 'Entrada',
    timestamp: new Date(Date.now() - 3600000 * 1.2).toISOString(),
    formattedTime: '07:38 AM',
    date: new Date().toISOString().split('T')[0],
    status: 'on_time',
    gate: 'Portón Principal (Entrada General)',
    registeredBy: 'Prof. Roberto Alarcón Díaz',
  },
  {
    id: 'acc-005',
    studentId: 'alu-005',
    studentName: 'Camila Elizabeth Torres Ortiz',
    enrollmentId: 'ALU-2026-005',
    grade: '2°',
    group: 'C',
    type: 'Entrada',
    timestamp: new Date(Date.now() - 3600000 * 1.1).toISOString(),
    formattedTime: '07:55 AM',
    date: new Date().toISOString().split('T')[0],
    status: 'on_time',
    gate: 'Portón 2 (Primaria / Vehicular)',
    registeredBy: 'Mtra. Elena Bustamante Ramos',
  },
];

export const INITIAL_NOTICES: DirectNotice[] = [
  {
    id: 'not-cit-001',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    tutorName: 'Vita Aurora Sanabria Lara',
    senderStaffName: 'Dra. Carmen Estrada Montes',
    senderRole: 'Dirección Escolar',
    category: 'Citatorio',
    title: '🚨 CITATORIO OFICIAL: Reunión de Seguimiento en Dirección',
    message: 'Se solicita atentamente la presencia del padre o tutor de la alumna en las oficinas de Dirección del plantel para dar seguimiento a acuerdos de desempeño académico y horario de talleres.',
    timestamp: new Date(Date.now() - 3600000 * 1).toISOString(),
    isRead: false,
    priority: 'Urgente',
    citatorioDate: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0], // 2 days from now
    citatorioTime: '08:30 AM',
    citatorioLocation: 'Dirección Escolar (Planta Alta)',
    requiresConfirmation: true,
    isConfirmedByTutor: false,
    targetScope: 'individual',
    targetGrade: '3°',
    targetGroup: 'A',
  },
  {
    id: 'not-rep-002',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    tutorName: 'Vita Aurora Sanabria Lara',
    senderStaffName: 'Lic. Fernando Quiroz Vega',
    senderRole: 'Prefectura Escolar & Disciplina',
    category: 'Reporte Disciplinario',
    title: 'Reporte Escolar: Uso indebido de dispositivo en laboratorio',
    message: 'Se hace de su conocimiento que la alumna utilizó el teléfono celular sin autorización docente durante la práctica de física. Se le solicitó guardar el equipo y se registra la presente llamada de atención preventiva.',
    timestamp: new Date(Date.now() - 3600000 * 6).toISOString(),
    isRead: false,
    priority: 'Importante',
    requiresConfirmation: true,
    isConfirmedByTutor: true,
    confirmedAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    targetScope: 'individual',
    targetGrade: '3°',
    targetGroup: 'A',
  },
  {
    id: 'not-avi-003',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    tutorName: 'Vita Aurora Sanabria Lara',
    senderStaffName: 'Dra. Carmen Estrada Montes',
    senderRole: 'Dirección Escolar',
    category: 'Aviso General',
    title: '📢 AVISO MASIVO: Convocatoria a Entrega de Boletas de Evaluación',
    message: 'Estimados Padres y Madres de Familia: Se les convoca a la entrega oficial de boletas del primer periodo el próximo viernes a las 09:00 AM en las aulas asignadas de cada grupo. Su asistencia es fundamental.',
    timestamp: new Date(Date.now() - 3600000 * 18).toISOString(),
    isRead: true,
    priority: 'Normal',
    requiresConfirmation: true,
    isConfirmedByTutor: true,
    confirmedAt: new Date(Date.now() - 3600000 * 10).toISOString(),
    targetScope: 'masivo',
  },
  {
    id: 'not-001',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    tutorName: 'Vita Aurora Sanabria Lara',
    senderStaffName: 'Mtra. Elena Bustamante Ramos',
    senderRole: 'Docente Titular 3° A',
    category: 'Conducta',
    title: 'Excelente participación en clase de Ciencias',
    message: 'Estimada Sra. Vita, le comparto una felicitación: Sofía demostró gran liderazgo y entusiasmo durante la presentación en equipo.',
    timestamp: new Date(Date.now() - 3600000 * 24).toISOString(),
    isRead: true,
    priority: 'Normal',
  },
  {
    id: 'not-002',
    studentId: 'alu-001',
    studentName: 'Sofía Mendoza Sanabria',
    tutorName: 'Vita Aurora Sanabria Lara',
    senderStaffName: 'Prof. Roberto Alarcón Díaz',
    senderRole: 'Responsable de Portón',
    category: 'Puntualidad',
    title: 'Registro de Ingreso Matutino Confirmado',
    message: 'Ingreso registrado exitosamente a las 07:42 AM por el Portón Principal.',
    timestamp: new Date(Date.now() - 3600000 * 2).toISOString(),
    isRead: true,
    priority: 'Normal',
  },
  {
    id: 'not-003',
    studentId: 'alu-003',
    studentName: 'Valentina Morales Herrera',
    tutorName: 'Ernesto Morales Vega',
    senderStaffName: 'Mtra. Elena Bustamante Ramos',
    senderRole: 'Docente de Grupo',
    category: 'Puntualidad',
    title: 'Aviso de Retardo en Portón 2',
    message: 'Se registró ingreso con retardo (08:05 AM). Favor de tomar precauciones viales.',
    timestamp: new Date(Date.now() - 3600000 * 1.5).toISOString(),
    isRead: false,
    priority: 'Importante',
  }
];

export const INITIAL_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-001',
    title: 'Aviso Importante: Protocolo de Climatización y Control de Acceso',
    category: 'Circular Oficial',
    date: '01 de Septiembre, 2026',
    author: 'Dirección / Control Escolar',
    summary: 'Mantenimiento del sistema de aire acondicionado y refuerzo en puertas de acceso.',
    content: 'Estimada comunidad escolar: Se ha completado la calibración del sistema de climatización y aire acondicionado en todas las aulas y auditorios para asegurar confort térmico. Asimismo, recordamos a todos los tutores portar la credencial digital QR para el acceso rápido y seguro.',
    attachmentName: 'Circular_04_Climatizacion_y_Accesos.pdf',
  },
  {
    id: 'ann-002',
    title: 'Primera Reunión General de Padres de Familia - Ciclo Escolar',
    category: 'Evento Escolar',
    date: '05 de Septiembre, 2026',
    author: 'Vita Aurora Sanabria Lara (Dirección)',
    summary: 'Presentación de metas académicas y comités de seguridad escolar.',
    content: 'Se convoca a los tutores de 1° a 6° grado al Auditorio Principal a las 08:30 AM para la presentación del programa pedagógico y uso de la plataforma digital móvil.',
    attachmentName: 'Orden_del_Dia_Junta_General.pdf',
  },
  {
    id: 'ann-003',
    title: 'Campaña de Vacunación y Revisión Médica Preventiva',
    category: 'Aviso General',
    date: '10 de Septiembre, 2026',
    author: 'Enfermería Escolar',
    summary: 'Jornada de salud escolar para el padrón estudiantil de 700 alumnos.',
    content: 'Con el apoyo del sector salud se aplicarán refuerzos de vacunación y chequeo de agudeza visual. Favor de enviar cartilla firmada en la sección de avisos.',
  },
];

export const INITIAL_EVENTS: SchoolEvent[] = [
  {
    id: 'evt-001',
    title: 'Junta de Padres de Familia (Primaria)',
    date: '2026-09-05',
    time: '08:30 AM',
    location: 'Auditorio Central',
    type: 'Reunión de Padres',
    description: 'Revisión del primer mes de clases y entrega de credenciales digitales.',
  },
  {
    id: 'evt-002',
    title: 'Feria de Ciencias y Tecnología Escolar',
    date: '2026-09-18',
    time: '09:00 AM - 01:30 PM',
    location: 'Explanada Principal',
    type: 'Académico',
    description: 'Exposición de proyectos de física, ecología y climatización.',
  },
  {
    id: 'evt-003',
    title: 'Suspensión Oficial de Labores Docentes',
    date: '2026-09-16',
    time: 'Todo el día',
    location: 'Plantel Escolar',
    type: 'Suspensión',
    description: 'Conmemoración de la Independencia Nacional.',
  },
];
